import React from 'react';

const Data = [
  { symbol: 'ข', class: 'high' },
  { symbol: 'ฃ', class: 'high' },
  { symbol: 'ฉ', class: 'high' },
  { symbol: 'ฐ', class: 'high' },
  { symbol: 'ถ', class: 'high' },
  { symbol: 'ผ', class: 'high' },
  { symbol: 'ฝ', class: 'high' },
  { symbol: 'ศ', class: 'high' },
  { symbol: 'ษ', class: 'high' },
  { symbol: 'ส', class: 'high' },
  { symbol: 'ห', class: 'high' },
  { symbol: 'ก', class: 'middle' },
  { symbol: 'จ', class: 'middle' },
  { symbol: 'ฎ', class: 'middle' },
  { symbol: 'ฏ', class: 'middle' },
  { symbol: 'ด', class: 'middle' },
  { symbol: 'ต', class: 'middle' },
  { symbol: 'บ', class: 'middle' },
  { symbol: 'ป', class: 'middle' },
  { symbol: 'อ', class: 'middle' },
  { symbol: 'ค', class: 'low' },
  { symbol: 'ฅ', class: 'low' },
  { symbol: 'ฆ', class: 'low' },
  { symbol: 'ง', class: 'low' },
  { symbol: 'ช', class: 'low' },
  { symbol: 'ซ', class: 'low' },
  { symbol: 'ฌ', class: 'low' },
  { symbol: 'ญ', class: 'low' },
  { symbol: 'ฑ', class: 'low' },
  { symbol: 'ฒ', class: 'low' },
  { symbol: 'ณ', class: 'low' },
  { symbol: 'ท', class: 'low' },
  { symbol: 'ธ', class: 'low' },
  { symbol: 'น', class: 'low' },
  { symbol: 'พ', class: 'low' },
  { symbol: 'ฟ', class: 'low' },
  { symbol: 'ภ', class: 'low' },
  { symbol: 'ม', class: 'low' },
  { symbol: 'ย', class: 'low' },
  { symbol: 'ร', class: 'low' },
  { symbol: 'ล', class: 'low' },
  { symbol: 'ว', class: 'low' },
  { symbol: 'ฬ', class: 'low' },
  { symbol: 'ฮ', class: 'low' },
];

export { Data };
