import React from 'react';

const Data = [
  { id: 0, symbol: 'ข', class: 'high' },
  { id: 1, symbol: 'ฃ', class: 'high' },
  { id: 2, symbol: 'ฉ', class: 'high' },
  { id: 3, symbol: 'ฐ', class: 'high' },
  { id: 4, symbol: 'ถ', class: 'high' },
  { id: 5, symbol: 'ผ', class: 'high' },
  { id: 6, symbol: 'ฝ', class: 'high' },
  { id: 7, symbol: 'ศ', class: 'high' },
  { id: 8, symbol: 'ษ', class: 'high' },
  { id: 9, symbol: 'ส', class: 'high' },
  { id: 10, symbol: 'ห', class: 'high' },
  { id: 11, symbol: 'ก', class: 'high' },
  { id: 12, symbol: 'จ', class: 'middle' },
  { id: 13, symbol: 'ฎ', class: 'middle' },
  { id: 14, symbol: 'ฏ', class: 'middle' },
  { id: 15, symbol: 'ด', class: 'middle' },
  { id: 16, symbol: 'ต', class: 'middle' },
  { id: 17, symbol: 'บ', class: 'middle' },
  { id: 18, symbol: 'ป', class: 'middle' },
  { id: 19, symbol: 'อ', class: 'middle' },
  { id: 20, symbol: 'ค', class: 'low' },
  { id: 21, symbol: 'ฅ', class: 'low' },
  { id: 22, symbol: 'ฆ', class: 'low' },
  { id: 23, symbol: 'ง', class: 'low' },
  { id: 24, symbol: 'ช', class: 'low' },
  { id: 25, symbol: 'ซ', class: 'low' },
  { id: 26, symbol: 'ฌ', class: 'low' },
  { id: 27, symbol: 'ญ', class: 'low' },
  { id: 28, symbol: 'ฑ', class: 'low' },
  { id: 29, symbol: 'ฒ', class: 'low' },
  { id: 30, symbol: 'ณ', class: 'low' },
  { id: 31, symbol: 'ท', class: 'low' },
  { id: 32, symbol: 'ธ', class: 'low' },
  { id: 33, symbol: 'น', class: 'low' },
  { id: 34, symbol: 'พ', class: 'low' },
  { id: 35, symbol: 'ฟ', class: 'low' },
  { id: 36, symbol: 'ภ', class: 'low' },
  { id: 37, symbol: 'ม', class: 'low' },
  { id: 38, symbol: 'ย', class: 'low' },
  { id: 39, symbol: 'ร', class: 'low' },
  { id: 40, symbol: 'ล', class: 'low' },
  { id: 41, symbol: 'ว', class: 'low' },
  { id: 42, symbol: 'ฬ', class: 'low' },
  { id: 43, symbol: 'ฮ', class: 'low' },
];

export { Data };
